version: "3.8"

services:
  cache-server-service:
    container_name: cache-server-container
    image: redis:7.4.1-bookworm
    # ports:
    #   - ${CACHE_SERVER_PORT}:6379
    command: ["redis-server", "--requirepass", "${CACHE_SERVER_PASSWORD}", "--bind", "0.0.0.0"]
    restart: always

  cache-server-monitor-service:
    container_name: cache-server-monitor-container
    image: redislabs/redisinsight:2.60
    ports:
      - ${CACHE_SERVER_MONITOR_PORT}:5540
    restart: always

  api-server-service:
    container_name: api-server-container
    image: takanarishimbo/local-transcription-web-app-api-server
    ports:
      - "${API_SERVER_PORT}:8000"
    environment:
      - CACHE_SERVER_ADDRESS=cache-server-container
      - CACHE_SERVER_PORT=6379
      - CACHE_SERVER_PASSWORD=${CACHE_SERVER_PASSWORD}
    depends_on:
      - cache-server-service
    restart: always

  ui-server-service:
    image: takanarishimbo/local-transcription-web-app-ui-server
    container_name: ui-server-container
    ports:
      - 5173:5173
    environment:
      - VITE_API_SERVER_ADDRESS=${API_SERVER_ADDRESS}
      - VITE_API_SERVER_PORT=${API_SERVER_PORT}
    depends_on:
      - api-server-service
    restart: always

  worker-service:
    container_name: worker-container
    image: takanarishimbo/local-transcription-web-app-worker
    runtime: nvidia
    environment:
      - CACHE_SERVER_ADDRESS=cache-server-container
      - CACHE_SERVER_PORT=6379
      - CACHE_SERVER_PASSWORD=${CACHE_SERVER_PASSWORD}
    depends_on:
      - cache-server-service
    restart: always
